# Generated by Django 6.0 on 2025-12-27 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='city',
            name='price',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('place_img', models.ImageField(upload_to='location_pics')),
                ('place_desc', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='cities.city')),
            ],
        ),
    ]
